name = "my-app"
main = "src/index.ts"
compatibility_date = "2024-12-30"

# compatibility_flags = [ "nodejs_compat" ]
# [vars]
# MY_VAR = "my-variable"

[vars]
DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYjRmMjA4ZWItNzIwNi00NjJmLTk2YjctYzU0YzA5ZDQ3MmIxIiwidGVuYW50X2lkIjoiNDI4ODQ5MjIxYTc4ZWI4OTRmYTJkNDljYjIxM2Q1Y2EzZmE2N2UwZGVlMDZjNjdhYzRiY2NlZDE3ZTY4NzkyYSIsImludGVybmFsX3NlY3JldCI6ImJlN2I2Y2Q2LTJjNWQtNGY0Zi04ZDE3LWEzMTcyMWJhZWQwNCJ9.l--uVKuFs_LlUN1iJUGUmbwdsOKh05GpruxT4FWTznI"
JWT_KEY = "keepitsecret"


# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1